// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "fabric8-jenkins-proxy-api": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-jenkins-proxy/internal/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-jenkins-proxy/internal/api
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// StatsController is the controller interface for the Stats actions.
type StatsController interface {
	goa.Muxer
	Clear(*ClearStatsContext) error
	Info(*InfoStatsContext) error
}

// MountStatsController "mounts" a Stats resource controller on the given service.
func MountStatsController(service *goa.Service, ctrl StatsController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewClearStatsContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Clear(rctx)
	}
	service.Mux.Handle("DELETE", "/api/clear/:namespace", ctrl.MuxHandler("clear", h, nil))
	service.LogInfo("mount", "ctrl", "Stats", "action", "Clear", "route", "DELETE /api/clear/:namespace")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewInfoStatsContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Info(rctx)
	}
	service.Mux.Handle("GET", "/api/info/:namespace", ctrl.MuxHandler("info", h, nil))
	service.LogInfo("mount", "ctrl", "Stats", "action", "Info", "route", "GET /api/info/:namespace")
}
