// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "fabric8-jenkins-proxy-api": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-jenkins-proxy/internal/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-jenkins-proxy/internal/api
// --version=v1.3.1

package app
